### ISSUE TITLE
[BUG]: "Unsecure" is really insecure

### ISSUE THREAD

**Issue by szepeviktor** [zizmorcore/zizmor#269]
### Pre-submission checks

- [X] I am **not** filing a feature request. These should be filed via the feature request form instead.
- [X] I have looked through the [open issues](https://github.com/woodruffw/zizmor/issues?q=is%3Aissue+is%3Aopen+) for a duplicate report.

### Expected behavior

https://github.com/search?q=repo%3Awoodruffw%2Fzizmor%20unsecure&type=code

### Actual behavior

https://github.com/search?q=repo%3Awoodruffw%2Fzizmor+insecure&type=code

### Reproduction steps

Would you merge a renaming PR?

**Comment by woodruffw** [comment]
Yes, please send one!
